import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { Pool } from 'pg';

export type LedgerKind = 'kill_reward' | 'purchase' | 'admin_adjustment' | 'refund';
export type InventoryStatus = 'bound' | 'pending_entry' | 'dropped' | 'consumed' | 'expired';
export interface EconomyPlayer { userKey: string; username: string; tiktokUserId?: string; kills: number; spent: number; available: number; }
export interface CatalogItem { id: string; slug: string; name: string; description: string; price: number; damage: number; range: number; durationMs: number; cooldownMs: number; active: boolean; icon: string; category: 'weapon' | 'consumable'; ammo: number; reloadMs: number; projectileSpeed: number; area: number; tactical: string; }
export interface InventoryItem { id: string; itemId: string; slug: string; name: string; status: InventoryStatus; purchasedAt: number; boundUntil: number; holderKey: string; x?: number; y?: number; }
export interface LedgerRow { id: string; userKey: string; kind: LedgerKind; amount: number; balanceAfter: number; referenceId: string; reason: string; createdAt: number; }
export interface EconomySnapshot { player: EconomyPlayer; inventory: InventoryItem[]; ledger: LedgerRow[]; }
interface LocalState { players: Record<string, EconomyPlayer>; ledger: LedgerRow[]; inventory: Record<string, InventoryItem>; }

export const STORE_CATALOG: CatalogItem[] = [
  { id: 'triple_life', slug: 'vida-tripla', name: 'Vida Tripla', description: 'Consumível: na próxima entrada em uma rodada, começa com 3x a vida base. Consome ao entrar; não cai nem acumula.', price: 180, damage: 0, range: 0, durationMs: 0, cooldownMs: 0, active: true, icon: '❤️‍🔥', category: 'consumable', ammo: 1, reloadMs: 0, projectileSpeed: 0, area: 0, tactical: 'Sustentação para uma entrada; não afeta respawn posterior.' },
  { id: 'pistol', slug: 'pistola', name: 'Pistola', description: 'Tiro rápido e barato para pressão curta/média.', price: 45, damage: 8, range: 480, durationMs: 180_000, cooldownMs: 1_800, active: true, icon: '🔫', category: 'weapon', ammo: 6, reloadMs: 5_500, projectileSpeed: 720, area: 0, tactical: 'Precisão e baixo custo.' },
  { id: 'machine_gun', slug: 'metralhadora', name: 'Metralhadora', description: 'Rajada de alto volume, dano baixo por tiro.', price: 95, damage: 4, range: 600, durationMs: 180_000, cooldownMs: 500, active: true, icon: '🔫', category: 'weapon', ammo: 20, reloadMs: 6_500, projectileSpeed: 900, area: 0, tactical: 'Supressão e combo de hits.' },
  { id: 'shotgun', slug: '12-escopeta', name: '12 / Escopeta', description: 'Disparo pesado de curto alcance com área de impacto.', price: 110, damage: 16, range: 260, durationMs: 180_000, cooldownMs: 3_500, active: true, icon: '💥', category: 'weapon', ammo: 2, reloadMs: 7_000, projectileSpeed: 520, area: 80, tactical: 'Burst e controle de espaço.' },
  { id: 'sniper', slug: 'sniper', name: 'Sniper', description: 'Longo alcance, dano alto e cadência lenta.', price: 180, damage: 35, range: 1000, durationMs: 180_000, cooldownMs: 5_000, active: true, icon: '🎯', category: 'weapon', ammo: 3, reloadMs: 9_000, projectileSpeed: 1300, area: 0, tactical: 'Pickoff de alvos expostos.' },
  { id: 'bazooka', slug: 'bazuca', name: 'Bazuca', description: 'Explosão lenta que pune agrupamentos.', price: 220, damage: 28, range: 620, durationMs: 180_000, cooldownMs: 7_000, active: true, icon: '🚀', category: 'weapon', ammo: 1, reloadMs: 10_000, projectileSpeed: 480, area: 110, tactical: 'Zona e dano em grupo.' },
  { id: 'land_mine', slug: 'mina-terrestre', name: 'Mina Terrestre', description: 'Planta uma mina; detona quando um adversário se aproxima.', price: 140, damage: 30, range: 0, durationMs: 180_000, cooldownMs: 2_000, active: true, icon: '💣', category: 'weapon', ammo: 2, reloadMs: 8_000, projectileSpeed: 0, area: 90, tactical: 'Armadilha e negação de rota.' },
  { id: 'dash_charge', slug: 'dash-charge', name: 'Carga Foguete', description: 'Acelera por 2,5 segundos ao usar.', price: 60, damage: 0, range: 0, durationMs: 180_000, cooldownMs: 8_000, active: true, icon: '🚀', category: 'consumable', ammo: 1, reloadMs: 0, projectileSpeed: 0, area: 0, tactical: 'Mobilidade e fuga.' },
];

export function normalizeTikTokHandle(raw: string): string {
  const s = String(raw || '').trim().toLowerCase();
  const fromUrl = s.match(/tiktok\.com\/@?([^/?#]+)/)?.[1] || s;
  return fromUrl.replace(/^@+/, '').replace(/[^a-z0-9._-]/g, '').slice(0, 64);
}
function now(): number { return Date.now(); }
function clone<T>(v: T): T { return JSON.parse(JSON.stringify(v)); }

export class EconomyStore {
  private pool: Pool | null = null;
  private local: LocalState = { players: {}, ledger: [], inventory: {} };
  private filePath: string;
  private ready = false;
  constructor(filePath = process.env.ECONOMY_LOCAL_PATH || path.resolve(process.cwd(), 'data/economy.json')) {
    this.filePath = filePath;
    this.loadLocal();
  }
  get persistent(): boolean { return !!this.pool; }
  async init(): Promise<void> {
    if (process.env.DATABASE_URL) {
      this.pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === 'false' ? false : { rejectUnauthorized: false }, max: 4 });
      await this.pool.query(`
        CREATE TABLE IF NOT EXISTS economy_players (user_key TEXT PRIMARY KEY, tiktok_username TEXT NOT NULL, tiktok_user_id TEXT, lifetime_kills INTEGER NOT NULL DEFAULT 0 CHECK (lifetime_kills >= 0), spent_kills INTEGER NOT NULL DEFAULT 0 CHECK (spent_kills >= 0), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
        CREATE TABLE IF NOT EXISTS economy_ledger (id UUID PRIMARY KEY, user_key TEXT NOT NULL REFERENCES economy_players(user_key), kind TEXT NOT NULL, amount INTEGER NOT NULL, balance_after INTEGER NOT NULL CHECK (balance_after >= 0), reference_id TEXT NOT NULL, reason TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(user_key, kind, reference_id));
        CREATE INDEX IF NOT EXISTS economy_ledger_user_created_idx ON economy_ledger(user_key, created_at DESC);
        CREATE TABLE IF NOT EXISTS economy_catalog (id TEXT PRIMARY KEY, slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, price INTEGER NOT NULL CHECK (price >= 0), damage INTEGER NOT NULL DEFAULT 0, range_px INTEGER NOT NULL DEFAULT 0, duration_ms INTEGER NOT NULL, cooldown_ms INTEGER NOT NULL DEFAULT 0, icon TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT true, category TEXT NOT NULL DEFAULT 'weapon', ammo INTEGER NOT NULL DEFAULT 1, reload_ms INTEGER NOT NULL DEFAULT 0, projectile_speed INTEGER NOT NULL DEFAULT 0, area_px INTEGER NOT NULL DEFAULT 0, tactical TEXT NOT NULL DEFAULT '', updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
        ALTER TABLE economy_catalog ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'weapon';
        ALTER TABLE economy_catalog ADD COLUMN IF NOT EXISTS ammo INTEGER NOT NULL DEFAULT 1;
        ALTER TABLE economy_catalog ADD COLUMN IF NOT EXISTS reload_ms INTEGER NOT NULL DEFAULT 0;
        ALTER TABLE economy_catalog ADD COLUMN IF NOT EXISTS projectile_speed INTEGER NOT NULL DEFAULT 0;
        ALTER TABLE economy_catalog ADD COLUMN IF NOT EXISTS area_px INTEGER NOT NULL DEFAULT 0;
        ALTER TABLE economy_catalog ADD COLUMN IF NOT EXISTS tactical TEXT NOT NULL DEFAULT '';
        CREATE TABLE IF NOT EXISTS economy_inventory (id UUID PRIMARY KEY, user_key TEXT NOT NULL REFERENCES economy_players(user_key), item_id TEXT NOT NULL REFERENCES economy_catalog(id), status TEXT NOT NULL, purchased_at TIMESTAMPTZ NOT NULL DEFAULT now(), bound_until TIMESTAMPTZ NOT NULL, holder_key TEXT NOT NULL, x REAL, y REAL, dropped_at TIMESTAMPTZ, picked_up_at TIMESTAMPTZ, operation_key TEXT UNIQUE NOT NULL);
        CREATE INDEX IF NOT EXISTS economy_inventory_holder_idx ON economy_inventory(holder_key, status);
      `);
      for (const item of STORE_CATALOG) await this.upsertCatalog(item);
      await this.pool.query(`UPDATE economy_catalog SET active=false,updated_at=now() WHERE slug IN ('iron-guard','marksman-rifle')`);
    } else {
      for (const item of STORE_CATALOG) this.localCatalog(item);
      this.flushLocal();
      console.warn('[ECONOMY] DATABASE_URL ausente: usando fallback local não persistente no Render free. Configure Postgres antes de produção.');
    }
    this.ready = true;
  }
  private loadLocal(): void { try { if (fs.existsSync(this.filePath)) this.local = JSON.parse(fs.readFileSync(this.filePath, 'utf8')); } catch { /* fresh */ } }
  private flushLocal(): void { fs.mkdirSync(path.dirname(this.filePath), { recursive: true }); const tmp = `${this.filePath}.tmp`; fs.writeFileSync(tmp, JSON.stringify(this.local, null, 2)); fs.renameSync(tmp, this.filePath); }
  private localCatalog(item: CatalogItem): void { /* catalog is code-defined in fallback */ void item; }
  private assertReady(): void { if (!this.ready) throw new Error('EconomyStore not initialized'); }
  private async upsertCatalog(item: CatalogItem): Promise<void> { await this.pool!.query(`INSERT INTO economy_catalog (id,slug,name,description,price,damage,range_px,duration_ms,cooldown_ms,icon,active,category,ammo,reload_ms,projectile_speed,area_px,tactical) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) ON CONFLICT (id) DO UPDATE SET slug=EXCLUDED.slug,name=EXCLUDED.name,description=EXCLUDED.description,price=EXCLUDED.price,damage=EXCLUDED.damage,range_px=EXCLUDED.range_px,duration_ms=EXCLUDED.duration_ms,cooldown_ms=EXCLUDED.cooldown_ms,icon=EXCLUDED.icon,active=EXCLUDED.active,category=EXCLUDED.category,ammo=EXCLUDED.ammo,reload_ms=EXCLUDED.reload_ms,projectile_speed=EXCLUDED.projectile_speed,area_px=EXCLUDED.area_px,tactical=EXCLUDED.tactical`, [item.id,item.slug,item.name,item.description,item.price,item.damage,item.range,item.durationMs,item.cooldownMs,item.icon,item.active,item.category,item.ammo,item.reloadMs,item.projectileSpeed,item.area,item.tactical]); }
  private key(handle: string): string { return normalizeTikTokHandle(handle); }
  async ensurePlayer(username: string, tiktokUserId?: string): Promise<string> { this.assertReady(); const userKey = this.key(username) || `unknown-${crypto.randomUUID()}`; if (this.pool) await this.pool.query(`INSERT INTO economy_players(user_key,tiktok_username,tiktok_user_id) VALUES($1,$2,$3) ON CONFLICT(user_key) DO UPDATE SET tiktok_username=EXCLUDED.tiktok_username,tiktok_user_id=COALESCE(EXCLUDED.tiktok_user_id,economy_players.tiktok_user_id),updated_at=now()`, [userKey,userKey,tiktokUserId]); else { this.local.players[userKey] ||= { userKey, username: userKey, tiktokUserId, kills: 0, spent: 0, available: 0 }; if (tiktokUserId) this.local.players[userKey].tiktokUserId = tiktokUserId; this.flushLocal(); } return userKey; }
  async recordKill(username: string, tiktokUserId: string | undefined, referenceId: string, reward = 1): Promise<EconomyPlayer | null> { const userKey = await this.ensurePlayer(username,tiktokUserId); const amount = Math.max(0, Math.floor(reward)); if (this.pool) { const c = await this.pool.connect(); try { await c.query('BEGIN'); const ins = await c.query(`INSERT INTO economy_ledger(id,user_key,kind,amount,balance_after,reference_id,reason) SELECT gen_random_uuid(),$1,'kill_reward',$2,p.lifetime_kills+$2,$3,'Kill confirmada' FROM economy_players p WHERE p.user_key=$1 ON CONFLICT(user_key,kind,reference_id) DO NOTHING RETURNING id`, [userKey,amount,referenceId]); if (ins.rowCount) await c.query(`UPDATE economy_players SET lifetime_kills=lifetime_kills+$2,updated_at=now() WHERE user_key=$1`, [userKey,amount]); await c.query('COMMIT'); } catch (e) { await c.query('ROLLBACK'); throw e; } finally { c.release(); } return this.getPlayer(userKey); }
    const p = this.local.players[userKey]; const exists = this.local.ledger.some(x => x.userKey === userKey && x.kind === 'kill_reward' && x.referenceId === referenceId); if (!exists) { p.kills += amount; p.available = Math.max(0,p.kills-p.spent); this.local.ledger.push({ id: crypto.randomUUID(), userKey, kind:'kill_reward', amount, balanceAfter:p.available, referenceId, reason:'Kill confirmada', createdAt:now() }); this.flushLocal(); } return clone(p); }
  async getPlayer(username: string): Promise<EconomyPlayer> { this.assertReady(); const userKey = this.key(username); if (this.pool) { const r = await this.pool.query(`SELECT user_key AS "userKey",tiktok_username AS username,tiktok_user_id AS "tiktokUserId",lifetime_kills AS kills,spent_kills AS spent,lifetime_kills-spent_kills AS available FROM economy_players WHERE user_key=$1`, [userKey]); return r.rows[0] || { userKey, username:userKey, kills:0, spent:0, available:0 }; } return this.local.players[userKey] ? clone(this.local.players[userKey]) : { userKey, username:userKey, kills:0, spent:0, available:0 }; }
  async getCatalog(): Promise<CatalogItem[]> { if (!this.pool) return clone(STORE_CATALOG); const r = await this.pool.query(`SELECT id,slug,name,description,price,damage,range_px AS range,duration_ms AS "durationMs",cooldown_ms AS "cooldownMs",icon,active,category,ammo,reload_ms AS "reloadMs",projectile_speed AS "projectileSpeed",area_px AS area,tactical FROM economy_catalog WHERE active=true ORDER BY price,id`); return r.rows; }
  async getCatalogItem(slug: string): Promise<CatalogItem | undefined> { const key = String(slug).trim().toLowerCase(); return (await this.getCatalog()).find(i => i.slug === key || i.name.toLowerCase() === key); }
  async purchase(username: string, slug: string, operationKey: string): Promise<{ ok:boolean; error?:string; item?:InventoryItem; player?:EconomyPlayer }> { const userKey = await this.ensurePlayer(username); const idem = String(operationKey || '').slice(0,100); if (!idem) return {ok:false,error:'operationKey obrigatório'}; if (this.pool) { const c=await this.pool.connect(); try { await c.query('BEGIN'); const existing=await c.query(`SELECT i.id,i.item_id AS "itemId",c.slug,c.name,i.status,extract(epoch from i.purchased_at)*1000 AS "purchasedAt",extract(epoch from i.bound_until)*1000 AS "boundUntil",i.holder_key AS "holderKey",i.x,i.y FROM economy_inventory i JOIN economy_catalog c ON c.id=i.item_id WHERE i.operation_key=$1`,[idem]); if(existing.rows[0]) { await c.query('COMMIT'); return {ok:true,item:existing.rows[0],player:await this.getPlayer(userKey)}; } const item=await c.query(`SELECT * FROM economy_catalog WHERE slug=$1 AND active=true`,[slug]); if(!item.rows[0]) { await c.query('ROLLBACK'); return {ok:false,error:'Item indisponível'}; } const price=item.rows[0].price; const p=await c.query(`SELECT * FROM economy_players WHERE user_key=$1 FOR UPDATE`,[userKey]); if(!p.rows[0] || p.rows[0].lifetime_kills-p.rows[0].spent_kills < price) { await c.query('ROLLBACK'); return {ok:false,error:'Saldo insuficiente'}; } const invId=crypto.randomUUID(); const status=item.rows[0].slug==='vida-tripla'?'pending_entry':'bound'; await c.query(`UPDATE economy_players SET spent_kills=spent_kills+$2,updated_at=now() WHERE user_key=$1`,[userKey,price]); await c.query(`INSERT INTO economy_ledger(id,user_key,kind,amount,balance_after,reference_id,reason) VALUES(gen_random_uuid(),$1,'purchase',$2,(SELECT lifetime_kills-spent_kills FROM economy_players WHERE user_key=$1),$3,$4)`,[userKey,-price,idem,`Compra ${slug}`]); await c.query(`INSERT INTO economy_inventory(id,user_key,item_id,status,bound_until,holder_key,operation_key) VALUES($1,$2,$3,$4,CASE WHEN $4='pending_entry' THEN now() ELSE now()+interval '3 minutes' END,$2,$5)`,[invId,userKey,item.rows[0].id,status,idem]); await c.query('COMMIT'); return {ok:true,item:{id:invId,itemId:item.rows[0].id,slug:item.rows[0].slug,name:item.rows[0].name,status,purchasedAt:now(),boundUntil:status==='pending_entry'?0:now()+180000,holderKey:userKey},player:await this.getPlayer(userKey)}; } catch(e){await c.query('ROLLBACK');throw e;} finally{c.release();} }
    const found=Object.values(this.local.inventory).find(i => (i as any).operationKey===idem); if(found) return {ok:true,item:clone(found),player:await this.getPlayer(userKey)}; const item=STORE_CATALOG.find(i=>i.slug===slug&&i.active); if(!item) return {ok:false,error:'Item indisponível'}; const p=this.local.players[userKey]; if(p.available<item.price) return {ok:false,error:'Saldo insuficiente'}; p.spent+=item.price;p.available=p.kills-p.spent;const status: InventoryStatus = item.slug==='vida-tripla'?'pending_entry':'bound';const inv:InventoryItem={id:crypto.randomUUID(),itemId:item.id,slug:item.slug,name:item.name,status,purchasedAt:now(),boundUntil:status==='pending_entry'?0:now()+180000,holderKey:userKey}; (inv as any).operationKey=idem;this.local.inventory[inv.id]=inv;this.local.ledger.push({id:crypto.randomUUID(),userKey,kind:'purchase',amount:-item.price,balanceAfter:p.available,referenceId:idem,reason:`Compra ${slug}`,createdAt:now()});this.flushLocal();return {ok:true,item:clone(inv),player:clone(p)};
  }
  async inventory(username: string): Promise<InventoryItem[]> { const userKey=this.key(username); if(this.pool){const r=await this.pool.query(`SELECT i.id,i.item_id AS "itemId",c.slug,c.name,i.status,extract(epoch from i.purchased_at)*1000 AS "purchasedAt",extract(epoch from i.bound_until)*1000 AS "boundUntil",i.holder_key AS "holderKey",i.x,i.y FROM economy_inventory i JOIN economy_catalog c ON c.id=i.item_id WHERE i.user_key=$1 OR i.holder_key=$1 ORDER BY i.purchased_at DESC`,[userKey]);return r.rows;}return Object.values(this.local.inventory).filter(i=>i.holderKey===userKey || (i as any).userKey===userKey).map(clone);
  }
  async consumeNextEntry(username: string, referenceId: string): Promise<boolean> { const userKey = this.key(username); if (this.pool) { const r = await this.pool.query(`UPDATE economy_inventory SET status='consumed',bound_until=now() WHERE id=(SELECT id FROM economy_inventory WHERE holder_key=$1 AND status='pending_entry' ORDER BY purchased_at ASC FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id`, [userKey]); return (r.rowCount ?? 0) > 0; } const item = Object.values(this.local.inventory).find(i => i.holderKey === userKey && i.status === 'pending_entry'); if (!item) return false; item.status = 'consumed'; item.boundUntil = now(); (item as any).consumedReferenceId = referenceId; this.flushLocal(); return true; }
  async markDropped(id: string, x: number, y: number): Promise<void> { if (this.pool) { await this.pool.query(`UPDATE economy_inventory SET status='dropped',x=$2,y=$3,dropped_at=now() WHERE id=$1 AND status='bound'`, [id,x,y]); return; } const i=this.local.inventory[id]; if(i){i.status='dropped';i.x=x;i.y=y;this.flushLocal();} }
  async markPickedUp(id: string, username: string): Promise<void> { const holder=await this.ensurePlayer(username); if(this.pool){await this.pool.query(`UPDATE economy_inventory SET status='bound',holder_key=$2,picked_up_at=now(),x=NULL,y=NULL,bound_until=GREATEST(bound_until,now()+interval '3 minutes') WHERE id=$1 AND status='dropped'`,[id,holder]);return;} const i=this.local.inventory[id];if(i&&i.status==='dropped'){i.status='bound';i.holderKey=holder;i.x=undefined;i.y=undefined;i.boundUntil=Math.max(i.boundUntil,now()+180000);this.flushLocal();} }
  async dropped(): Promise<InventoryItem[]> { if(this.pool){const r=await this.pool.query(`SELECT i.id,i.item_id AS "itemId",c.slug,c.name,i.status,extract(epoch from i.purchased_at)*1000 AS "purchasedAt",extract(epoch from i.bound_until)*1000 AS "boundUntil",i.holder_key AS "holderKey",i.x,i.y FROM economy_inventory i JOIN economy_catalog c ON c.id=i.item_id WHERE i.status='dropped'`);return r.rows;}return Object.values(this.local.inventory).filter(i=>i.status==='dropped').map(clone); }
  async ledger(username: string, limit=50): Promise<LedgerRow[]> { const userKey=this.key(username); if(this.pool){const r=await this.pool.query(`SELECT id,user_key AS "userKey",kind,amount,balance_after AS "balanceAfter",reference_id AS "referenceId",reason,extract(epoch from created_at)*1000 AS "createdAt" FROM economy_ledger WHERE user_key=$1 ORDER BY created_at DESC LIMIT $2`,[userKey,Math.min(100,Math.max(1,limit))]);return r.rows;}return this.local.ledger.filter(x=>x.userKey===userKey).slice(-limit).reverse().map(clone); }
  async adminAdjust(username: string, amount: number, reason: string, operationKey: string): Promise<{ok:boolean;error?:string;player?:EconomyPlayer}> { if(!reason?.trim()) return {ok:false,error:'Motivo obrigatório'}; const p=await this.ensurePlayer(username); if(this.pool){const c=await this.pool.connect();try{await c.query('BEGIN');const exists=await c.query(`SELECT 1 FROM economy_ledger WHERE user_key=$1 AND kind='admin_adjustment' AND reference_id=$2`,[p,operationKey]);if(!exists.rowCount){const row=await c.query(`UPDATE economy_players SET lifetime_kills=lifetime_kills+$2,updated_at=now() WHERE user_key=$1 AND lifetime_kills+$2-spent_kills>=0 RETURNING lifetime_kills-spent_kills AS available`,[p,Math.floor(amount)]);if(!row.rowCount){await c.query('ROLLBACK');return {ok:false,error:'Ajuste deixaria saldo negativo'};}await c.query(`INSERT INTO economy_ledger(id,user_key,kind,amount,balance_after,reference_id,reason) VALUES(gen_random_uuid(),$1,'admin_adjustment',$2,(SELECT lifetime_kills-spent_kills FROM economy_players WHERE user_key=$1),$3,$4)`,[p,Math.floor(amount),operationKey,reason.trim()]);}await c.query('COMMIT');return {ok:true,player:await this.getPlayer(p)};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}} const pl=this.local.players[p];if(this.local.ledger.some(x=>x.userKey===p&&x.kind==='admin_adjustment'&&x.referenceId===operationKey))return{ok:true,player:clone(pl)};const a=Math.floor(amount);if(pl.available+a<0)return{ok:false,error:'Ajuste deixaria saldo negativo'};pl.kills+=Math.max(0,a);pl.spent+=Math.max(0,-a);pl.available=pl.kills-pl.spent;this.local.ledger.push({id:crypto.randomUUID(),userKey:p,kind:'admin_adjustment',amount:a,balanceAfter:pl.available,referenceId:operationKey,reason:reason.trim(),createdAt:now()});this.flushLocal();return{ok:true,player:clone(pl)}; }
  async adminSummary(): Promise<{players: EconomyPlayer[]; inventory: InventoryItem[]; ledger: LedgerRow[]}> { if(this.pool){const p=await this.pool.query(`SELECT user_key AS "userKey",tiktok_username AS username,tiktok_user_id AS "tiktokUserId",lifetime_kills AS kills,spent_kills AS spent,lifetime_kills-spent_kills AS available FROM economy_players ORDER BY lifetime_kills DESC LIMIT 500`);const i=await this.pool.query(`SELECT i.id,i.item_id AS "itemId",c.slug,c.name,i.status,extract(epoch from i.purchased_at)*1000 AS "purchasedAt",extract(epoch from i.bound_until)*1000 AS "boundUntil",i.holder_key AS "holderKey",i.x,i.y FROM economy_inventory i JOIN economy_catalog c ON c.id=i.item_id ORDER BY i.purchased_at DESC LIMIT 500`);const l=await this.pool.query(`SELECT id,user_key AS "userKey",kind,amount,balance_after AS "balanceAfter",reference_id AS "referenceId",reason,extract(epoch from created_at)*1000 AS "createdAt" FROM economy_ledger ORDER BY created_at DESC LIMIT 500`);return{players:p.rows,inventory:i.rows,ledger:l.rows};}return{players:Object.values(this.local.players).map(clone),inventory:Object.values(this.local.inventory).map(clone),ledger:this.local.ledger.slice(-500).reverse().map(clone)}; }
  async close(): Promise<void> { await this.pool?.end(); }
}
